# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 03:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe7\xa7\xb0\xe5\x8f\x8a\xe4\xbb\xbb\xe8\xaf\xbe\xe8\x80\x81\xe5\xb8\x88')),
                ('course_time', models.CharField(max_length=50, verbose_name=b'\xe5\xbc\x80\xe8\xaf\xbe\xe6\x97\xb6\xe9\x97\xb4')),
                ('course_index', models.CharField(max_length=50, verbose_name=b'\xe4\xb8\x8a\xe8\xaf\xbe\xe6\x97\xb6\xe9\x97\xb4')),
                ('course_subject', models.CharField(choices=[(b'IT', b'\xe4\xbf\xa1\xe6\x81\xaf\xe7\xa7\x91\xe5\xad\xa6\xe4\xb8\x8e\xe6\x8a\x80\xe6\x9c\xaf\xe5\xad\xa6\xe9\x99\xa2'), (b'EE', b'\xe7\x94\xb5\xe6\xb0\x94\xe5\xb7\xa5\xe7\xa8\x8b\xe5\xad\xa6\xe9\x99\xa2'), (b'CE', b'\xe5\x9c\x9f\xe6\x9c\xa8\xe5\xb7\xa5\xe7\xa8\x8b\xe5\xad\xa6\xe9\x99\xa2'), (b'MA', b'\xe6\x95\xb0\xe5\xad\xa6\xe5\xad\xa6\xe9\x99\xa2'), (b'ME', b'\xe6\x9c\xba\xe6\xa2\xb0\xe5\xb7\xa5\xe7\xa8\x8b\xe5\xad\xa6\xe9\x99\xa2'), (b'PH', b'\xe7\x89\xa9\xe7\x90\x86\xe5\xad\xa6\xe9\x99\xa2'), (b'HS', b'\xe4\xba\xba\xe6\x96\x87\xe5\xad\xa6\xe9\x99\xa2')], max_length=2, verbose_name=b'\xe5\xbc\x80\xe8\xaf\xbe\xe5\xad\xa6\xe9\x99\xa2')),
                ('course_description', models.TextField(max_length=200, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe7\xae\x80\xe4\xbb\x8b')),
                ('course_consume', models.IntegerField(verbose_name=b'\xe5\x91\xa8\xe5\xad\xa6\xe6\x97\xb6')),
                ('course_choose', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u897f\u5357\u4ea4\u5927\u9009\u8bfe\u7cfb\u7edf',
            },
        ),
    ]
